tool and start commands

diff --git a/ideal-build-tool/buildtool b/ideal-build-tool/buildtool
--- a/ideal-build-tool/buildtool
+++ b/ideal-build-tool/buildtool
@@ -19,6 +19,7 @@ set -e
 declare -a _bt_cleanup_folders
 declare -A _bt_task_map
 _bt_build_command=""
+_bt_start_command=""
 
 #
 #
@@ -49,6 +50,28 @@ _bt_split_on_with() {
 
 #
 #
+# Tool checkers
+#
+#
+
+_bt_check_tool_in_path() {
+  tool_name="$1"
+  tool_expected_version="$2"
+
+  if ! command -v $tool_name >/dev/null 2>/dev/null; then 
+    echo "Tool not found: $tool_name"
+    exit 1
+  fi
+
+  tool_version=$(${tool_name} --version)
+  if [[ "$tool_version" != *${tool_expected_version}* ]]; then 
+    echo "Tool is the wrong version: $tool_name $tool_version"
+    echo "Expected $tool_expected_version"
+  fi
+}
+
+#
+#
 # State setters
 #
 #
@@ -58,13 +81,18 @@ _bt_set_build_command() {
   _bt_build_command="$post_with"
 }
 
+_bt_set_start_command() {
+  eval $(_bt_split_on_with $*)
+  _bt_start_command="$post_with"
+}
+
 _bt_create_task_command() {
   eval $(_bt_split_on_with $*)
-  _bt_task_map[$pre_with]=$post_with
+  _bt_task_map[$pre_with]="$post_with"
 }
 
 _bt_declare_cleanup_folders() {
-  _bt_cleanup_folders=$@
+  _bt_cleanup_folders=($*)
 }
 
 #
@@ -75,6 +103,14 @@ _bt_declare_cleanup_folders() {
 
 _bt_invoke_task() {
   sh -c "${_bt_task_map[$*]}"
+}
+
+_bt_invoke_build_command() {
+  sh -c "${_bt_build_command}"
+}
+
+_bt_invoke_start_command() {
+  sh -c "${_bt_start_command}"
 }
 
 _bt_invoke_cleanup() {
@@ -104,6 +140,7 @@ usage:
             -v:   enable verbose mode for the build tool
     -h, --help:   get this help text
          build:   build $projectName
+         start:   start the dev mode for $projectName
            run:   start a script for $projectName
          clean:   remove output folders
 
@@ -135,7 +172,7 @@ _bt_parse_cli_and_invoke() {
   while [[ $# -gt 0 ]]; do
     case $1 in
       -v)
-        set +x
+        set -x
         ;;
       -h|--help)
         _bt_usage
@@ -143,6 +180,10 @@ _bt_parse_cli_and_invoke() {
         ;;
       build)
         _bt_invoke_build_command
+        didSomething=1
+        ;;
+      start)
+        _bt_invoke_start_command
         didSomething=1
         ;;
       run)
@@ -171,3 +212,5 @@ alias build="_bt_set_build_command"
 alias run="_bt_create_task_command"
 alias cleanup="_bt_declare_cleanup_folders"
 alias woot='_bt_parse_cli_and_invoke $*'
+alias tool='_bt_check_tool_in_path'
+alias start='_bt_set_start_command'
