setup check framework

diff --git a/ideal-build-tool/buildtool b/ideal-build-tool/buildtool
--- a/ideal-build-tool/buildtool
+++ b/ideal-build-tool/buildtool
@@ -17,6 +17,7 @@ set -e
 #
 
 declare -a _bt_cleanup_folders
+declare -a _bt_setup_checks
 declare -A _bt_task_map
 _bt_build_command=""
 _bt_start_command=""
@@ -91,6 +92,10 @@ _bt_create_task_command() {
   _bt_task_map[$pre_with]="$post_with"
 }
 
+_bt_create_setup_check() {
+  _bt_setup_checks+=("$*")
+}
+
 _bt_declare_cleanup_folders() {
   _bt_cleanup_folders=($*)
 }
@@ -119,6 +124,12 @@ _bt_invoke_cleanup() {
   done
 }
 
+_bt_invoke_setup_checks() {
+  for check in $_bt_setup_checks; do 
+    sh -c "${check}" || echo "Error: $check failed." && exit 1
+  done
+}
+
 #
 #
 # CLI
@@ -139,17 +150,25 @@ usage:
 
             -v:   enable verbose mode for the build tool
     -h, --help:   get this help text
-         build:   build $projectName
-         start:   start the dev mode for $projectName
-           run:   start a script for $projectName
-         clean:   remove output folders
-
-available scripts: 
 EOF
 
-  for task in ${(k)_bt_task_map}; do
-    echo "$toolName $task"
-  done
+  if [[ -n "$_bt_build_command" ]]; then 
+    echo "         build:   build $projectName"
+  fi
+  if [[ -n "$_bt_start_command" ]]; then 
+    echo "         start:   start the dev mode for $projectName"
+  fi
+  if [[ -n "${_bt_clean_folders}" ]]; then
+    echo  "         clean:   remove output folders"
+  fi
+  if [[ -n "${(k)_bt_task_map}" ]]; then 
+    echo "          run:   start a script for $projectName"
+    echo
+    echo "available scripts: "
+    for task in ${(k)_bt_task_map}; do
+      echo "$toolName $task"
+    done
+  fi
 }
 
 _bt_fuzzy_ui() {
@@ -168,6 +187,9 @@ _bt_fallback() {
 
 
 _bt_parse_cli_and_invoke() {
+
+  _bt_invoke_setup_checks
+
   local didSomething=0
   while [[ $# -gt 0 ]]; do
     case $1 in
@@ -214,3 +236,4 @@ alias cleanup="_bt_declare_cleanup_folders"
 alias woot='_bt_parse_cli_and_invoke $*'
 alias tool='_bt_check_tool_in_path'
 alias start='_bt_set_start_command'
+alias check='_bt_create_setup_check'
